ARG BASE_TAG="develop"
FROM linkease/core-ubuntu-arm64:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# Add Kasm Branding
RUN cp /usr/share/extra/backgrounds/bg_kasm.png /usr/share/extra/backgrounds/bg_default.png
RUN cp /usr/share/extra/icons/icon_kasm.png /usr/share/extra/icons/icon_default.png
RUN sed -i 's/ubuntu-mono-dark/elementary-xfce/g' $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

# Install Utilities
COPY ./src/ubuntu/install/misc $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/install_tools.sh && rm -rf $INST_SCRIPTS/misc/

# Install Chromium
COPY ./src/ubuntu/install/chromium $INST_SCRIPTS/chromium/
RUN bash $INST_SCRIPTS/chromium/install_chromium.sh && rm -rf $INST_SCRIPTS/chromium/

# Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

# Install Custom Certificate Authority
# COPY ./src/ubuntu/install/certificates $INST_SCRIPTS/certificates/
# RUN bash $INST_SCRIPTS/certificates/install_ca_cert.sh && rm -rf $INST_SCRIPTS/certificates/


# Install Remina
COPY ./src/ubuntu/install/remmina $INST_SCRIPTS/remmina/
RUN bash $INST_SCRIPTS/remmina/install_remmina.sh  && rm -rf $INST_SCRIPTS/remmina/

RUN mkdir $HOME/.config/remmina/
COPY ./src/ubuntu/install/remmina/remmina.pref $HOME/.config/remmina/remmina.pref
RUN chown -R 1000:1000 $HOME/.config/remmina/


# Overwrite vnc
COPY ./src/common/startup_scripts/vnc_startup.sh /dockerstartup/vnc_startup.sh
RUN chmod 755 /dockerstartup/vnc_startup.sh

ENV XMODIFIERS="@im=ibus"
ENV QT_IM_MODULE="ibus"
ENV GTK_IM_MODULE="ibus"

RUN mkdir -p /tmp/tools/
COPY ./src/custom/ttf-wps-fonts /tmp/tools/ttf-wps-fonts
COPY ./src/custom/wps-office_11.1.0.10702_arm64.deb /tmp/tools/
RUN ls /tmp/tools && bash /tmp/tools/ttf-wps-fonts/install.sh
RUN apt install -y libxkbcommon-x11-0 libxcb-xinerama0 libxslt-dev ibus ibus-sunpinyin ttf-mscorefonts-installer fonts-wqy-zenhei ibus-gtk ibus-gtk3
RUN dpkg -i /tmp/tools/wps-office_11.1.0.10702_arm64.deb && apt install -f && rm -rf /tmp/tools

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
